language: python
os: linux
dist: jammy
jobs:
  include:
    - python: "3.11"
      env: TOXENV=check,py311
    - python: "3.10"
      env: TOXENV=py310
    - python: "3.9"
      env: TOXENV=py39
    - python: "3.8"
      env: TOXENV=py38
    # - python: "3.7"
    #   env: TOXENV=py37
    - python: "3.12-dev"
      env: TOXENV=py312
  allow_failures:
    - python: "3.12-dev"
      env: TOXENV=py312

install:
  - pip install tox-travis coveralls coverage
  # - pip install tox-travis flake8 coveralls coverage isort
script:
  - tox
after_success:
  - coverage combine
  - coveralls
