[tool.black]
line-length = 88
# py36 = false  # don't strip 'u' from native strings
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.tox
  | \.venv
  | \.eggs
  | \.cache
  | build
  | __pycache__
  | dist
  | \.*

)/
'''


[tool.isort]
# See https://black.readthedocs.io/en/stable/compatible_configs.html
profile = "black"
src_paths = ["nutree", "tests"]

[tool.ruff]
# Decrease the maximum line length to 79 characters.
# line-length = 79
# Support Python 3.10+.
target-version = "py37"
src = ["nutree", "tests"]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "G",   # flake8-logging-format
  "UP",  # pyupgrade
  # "D",   # pydocstyle
]

# [tool.ruff.pydocstyle]
# convention = "google"
